import tkinter as tk, sys, os, h5_util as h5u

from tkinter import filedialog as fd

def preprocess_xrf_xrt_data(synchrotron,
                            synchrotron_beamline,
                            create_aggregate_xrf_xrt_files_enabled,
                            pre_existing_alignment_norm_mass_calibration_file_enabled,
                            pre_existing_alignment_norm_mass_calibration_file_path,
                            norm_enabled,
                            mass_calibration_enabled,
                            mass_calibration_dir,
                            mass_calibration_filepath,
                            mass_calibration_elements,
                            areal_mass_density_mass_calibration_elements_g_cm2,
                            iterative_reproj_enabled):
        
    if create_aggregate_xrf_xrt_files_enabled:
        # xrf_file_array = ['/raid/users/roter/Jacobsen/img.dat/2xfm_0030.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0031.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0032.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0033.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0034.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0117.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0118.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0037.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0038.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0039.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0040.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0047.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0042.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0048.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0049.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0050.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0051.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0052.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0053.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0054.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0055.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0056.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0057.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0058.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0059.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0060.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0094.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0095.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0096.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0097.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0098.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0099.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0100.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0101.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0102.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0103.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0104.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0105.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0106.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0107.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0108.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0109.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0110.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0111.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0112.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0113.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0114.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0115.mda.h5',
        #                   '/raid/users/roter/Jacobsen/img.dat/2xfm_0116.mda.h5']
        
        xrf_file_array = ['/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235324.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235327.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235330.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235333.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235336.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235339.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235342.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235345.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235348.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235351.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235354.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235358.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235364.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235374.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235377.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235386.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235389.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235392.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235395.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235398.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235401.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235404.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235407.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235410.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235413.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235416.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235419.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235422.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235425.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235428.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235431.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235434.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235437.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235440.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235443.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235446.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235449.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235452.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235455.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235458.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235461.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235464.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235467.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235470.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235473.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235476.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235479.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235482.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235485.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235488.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235491.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235494.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235497.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235500.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235503.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235506.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235509.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235512.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235515.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235518.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235546.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235549.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235552.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235555.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235558.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235561.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235564.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235567.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235570.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235573.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235576.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235579.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235582.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235585.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235588.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235592.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235598.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235601.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235604.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235607.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235610.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235613.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235616.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235619.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235622.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235625.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235628.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235631.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235637.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235640.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235643.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235646.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235649.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235652.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235655.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235658.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235664.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235667.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235670.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/xrf/scan2D_235673.h5']
        xrt_file_array = ['/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235324.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235327.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235330.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235333.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235336.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235339.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235342.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235345.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235348.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235351.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235354.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235358.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235364.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235374.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235377.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235386.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235389.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235392.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235395.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235398.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235401.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235404.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235407.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235410.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235413.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235416.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235419.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235422.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235425.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235428.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235431.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235434.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235437.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235440.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235443.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235446.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235449.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235452.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235455.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235458.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235461.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235464.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235467.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235470.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235473.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235476.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235479.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235482.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235485.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235488.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235491.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235494.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235497.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235500.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235503.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235506.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235509.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235512.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235515.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235518.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235546.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235549.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235552.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235555.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235558.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235561.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235564.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235567.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235570.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235573.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235576.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235579.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235582.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235585.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235588.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235592.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235598.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235601.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235604.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235607.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235610.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235613.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235616.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235619.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235622.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235625.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235628.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235631.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235637.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235640.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235643.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235646.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235649.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235652.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235655.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235658.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235664.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235667.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235670.h5',
                          '/raid/users/roter/Jacobsen-nslsii/data/ptycho/h5_data/scan_235673.h5']

        # xrt_file_array = xrf_file_array.copy()
        # root = tk.Tk()

        # xrf_file_array = fd.askopenfilenames(parent = root, title = "Choose XRF files to aggregate.", filetypes = [('HDF5 files', '*.h5')])
        # xrt_file_array = fd.askopenfilenames(parent = root, title = "Choose XRT files to aggregate.", filetypes = [('HDF5 files', '*.h5')])

        if xrf_file_array == '' or xrt_file_array == '':
            print('Error: XRF and/or XRT filename array empty. Exiting program...')
            
            sys.exit()

        xrf_array_dir = os.path.dirname(xrf_file_array[0])
        xrt_array_dir = os.path.dirname(xrt_file_array[0])

        output_xrf_filepath = os.path.join(xrf_array_dir, f'{synchrotron_beamline}_aggregate_xrf.h5')
        output_xrt_filepath = os.path.join(xrt_array_dir, f'{synchrotron_beamline}_aggregate_xrt.h5')

        print('Creating aggregate XRF data file...')

        if synchrotron.lower() == 'nsls-ii':
            us_ic, nx, ny = h5u.create_aggregate_xrf_h5(xrf_file_array, 
                                                              output_xrf_filepath, 
                                                              synchrotron, 
                                                              us_ic = True) # us_ic_array only returned since that data is not present in NSLS-II ptychography files

            print('Creating aggregate XRT data file...')

            h5u.create_aggregate_xrt_h5(xrt_file_array, 
                                        output_xrt_filepath, 
                                        synchrotron, 
                                        nx = nx, 
                                        ny = ny, 
                                        us_ic = us_ic)
        
        else:
            h5u.create_aggregate_xrf_h5(xrf_file_array, 
                                        output_xrf_filepath, 
                                        synchrotron)

            print('Creating aggregate XRT data file...')

            h5u.create_aggregate_xrt_h5(xrt_file_array, 
                                        output_xrt_filepath, 
                                        synchrotron)
        
        # sys.exit()

    # if mass_calibration_enabled:
    #     print('Mass calibrating incident beam intensity...')

    #     if synchrotron == 'aps':
            